#!/bin/bash
# ==============================================================================
# File: watchdog.sh
# Brief: 宿主機守護行程 (First Boot、Docker 監控、OTA A/B 槽切換與自動回滾)
# Author: Jim Hsu (aba0971@gmail.com)
# Created Time: 2026-09-14 00:00:00
# Copyright: Copyright (c) 2026 CQI (CHENGQI Co., Ltd.)
#            All rights reserved.
# Notice: 由 systemd (__PROJ_NAME_LOWER__.service) 於開機時自動喚醒執行
# ==============================================================================

# ==============================================================================
# ⚙️ 全域部署與識別組態 (Global Deployment & Identity Configuration)
# ==============================================================================
ID_MODE=1                         # 1: 實體硬體後 8 碼 (無碰撞風險) | 2: 資安鹽值雜湊後 8 碼模式
ID_SALT="CQI___PROJ_NAME_UPPER__" # 獨立資安鹽值參數 (僅在 ID_MODE=2 時生效)
ID_MAX_LEN=10                     # 核心識別碼長度限制 (包含前綴碼，確保整體 DEVICE_ID 固定長度)
ID_PREFIX="00"                    # 專案/功能前綴碼 (2碼前綴 + 8碼核心識別 = 10碼固定長度)

# ==============================================================================
# 📂 實體路徑與環境變數配置 (Path & Environment Configuration)
# ==============================================================================
BASE_DIR="/opt/__PROJ_NAME_LOWER__"
SLOT_A="$BASE_DIR/slot_A"
SLOT_B="$BASE_DIR/slot_B"
CURRENT_LINK="$BASE_DIR/current"
DATA_DIR="$BASE_DIR/data"
ENV_FILE="$DATA_DIR/.env"
BOOT_FILE="$DATA_DIR/.boot_ok"
HEALTH_FILE="$DATA_DIR/.health_ok"
OTA_READY_FILE="$DATA_DIR/.ota_ready"
UPDATE_TAR="$DATA_DIR/ota_cache/update.tar.gz"

echo "[WATCHDOG] Starting __PROJECT_NAME__ Watchdog..."

# ==============================================================================
# 1. 首次開機 (First Boot) 探測與 .env 生成
# ==============================================================================
if [ ! -f "$ENV_FILE" ]; then
	echo "[WATCHDOG] First boot detected! Initializing hardware profile..."

	# A. 硬體型號探測 (Hardware Model Detection)
	HW_MODEL="PC_WSL_DEV"
	COMPOSE_FILE="docker-compose.dev.yml"

	if [ -f "/sys/firmware/devicetree/base/model" ]; then
		MODEL_STR=$(cat /sys/firmware/devicetree/base/model | tr -d '\0')
		if [[ "$MODEL_STR" == *"Raspberry Pi 5"* ]]; then
			HW_MODEL="Raspberry Pi 5"
			COMPOSE_FILE="docker-compose.pi.yml"
		elif [[ "$MODEL_STR" == *"Raspberry Pi Zero 2"* ]]; then
			HW_MODEL="Raspberry Pi Zero 2 W"
			COMPOSE_FILE="docker-compose.pi.yml"
		fi
	fi
	echo "[WATCHDOG] Hardware Model Detected: $HW_MODEL"

	# B. 硬體唯一識別碼生成 (Device ID Generation)
	# ==============================================================================
	# 🆔 DEVICE ID GENERATION (工業級唯一識別碼生成核心)
	# ==============================================================================

	echo "[INFO] Initializing device identifier generation..."

	# 1. 採集硬體原始識別碼 (優先讀取 CPU 序號，次級備援讀取網卡 MAC)
	HW_RAW_ID=""

	if [ -f /proc/cpuinfo ]; then
		# 提取樹莓派 CPU 唯一的 16 位元實體序號
		HW_RAW_ID=$(grep -i "serial" /proc/cpuinfo | awk '{print $3}')
	fi

	# 若無 CPU 序號或讀取到虛擬機全零序號，則切換至網卡 MAC 位址
	if [ -z "$HW_RAW_ID" ] || [ "$HW_RAW_ID" = "0000000000000000" ]; then
		if [ -f /sys/class/net/eth0/address ]; then
			# 讀取 MAC 並透過 tr 清除所有冒號 ":" 確保字串純淨
			HW_RAW_ID=$(cat /sys/class/net/eth0/address | tr -d ':')
		else
			echo "[ERROR] Hardware identifier source not found!"
			HW_RAW_ID="UNKNOWNRAW"
		fi
	fi

	# 清除硬體識別碼中可能包含的任何空白字元
	CLEAN_HW_ID=$(echo -n "$HW_RAW_ID" | tr -d '[:space:]')

	# 2. 依據設定模式計算 8 碼核心識別碼 (DEVICE_HASH)
	if [ "$ID_MODE" -eq 1 ]; then
		# 【選項 1】直接截取實體硬體序號或 MAC 的後 8 碼，並強制轉換為全大寫
		DEVICE_HASH=$(echo -n "$CLEAN_HW_ID" | tail -c 8 | tr '[:lower:]' '[:upper:]')
		echo "[INFO] Identity Mode 1 selected: Direct Truncation."
	else
		# 【選項 2】注入資安鹽值進行不對稱雜湊，並截取 SHA256 最終結果的最後 8 個字元，全大寫
		FULL_HASH=$(echo -n "${ID_SALT}${CLEAN_HW_ID}" | sha256sum | awk '{print $1}')
		DEVICE_HASH=$(echo -n "$FULL_HASH" | tail -c 8 | tr '[:lower:]' '[:upper:]')
		echo "[INFO] Identity Mode 2 selected: Salted SHA256 Truncation."
	fi

	# 3. 組合前綴碼與核心識別碼，產生最終 10 碼通訊識別元
	DEVICE_ID="${ID_PREFIX}${DEVICE_HASH}"

	# 4. 強制長度防呆校驗 (熔斷防護網)
	if [ "${#DEVICE_ID}" -ne "$ID_MAX_LEN" ]; then
		echo "[FATAL] Device ID length validation failed! Expected $ID_MAX_LEN, got ${#DEVICE_ID}."
		echo "[FATAL] Aborting watchdog startup to prevent corrupted data transmission."
		exit 1
	fi

	echo "[SUCCESS] Device ID successfully locked: ${DEVICE_ID}"

	# C. 寫入持久化 .env 檔案
	cat <<EOF >"$ENV_FILE"
# Auto-generated by Watchdog on First Boot
HW_MODEL="$HW_MODEL"
DEVICE_ID="$DEVICE_ID"
DOCKER_COMPOSE_FILE="$COMPOSE_FILE"
EOF
	echo "[WATCHDOG] First boot initialization complete."
fi

source "$ENV_FILE"

# ==============================================================================
# 2. 定義當前槽位與備用槽位 (A/B Slot Calculation)
# ==============================================================================
CURRENT_SLOT=$(readlink "$CURRENT_LINK")
if [ "$CURRENT_SLOT" == "$SLOT_A" ]; then
	ALT_SLOT="$SLOT_B"
else
	ALT_SLOT="$SLOT_A"
fi

# ==============================================================================
# 3. 核心啟動與健康度驗證函數 (Start & Verify)
# ==============================================================================
start_and_verify() {
	cd "$CURRENT_LINK" || return 1
	# 將資料區的 .env 軟連結到當前槽位供 Docker 讀取
	ln -sfn "$ENV_FILE" "$CURRENT_LINK/.env"

	# 🛡️ 【外層 NTP 校時防線】：等待系統時間校正 (年份須 >= 2026)
	echo "[WATCHDOG] Validating system clock synchronization..."
	while [ "$(date +%Y)" -lt 2026 ]; do
		echo "[WATCHDOG] System clock year < 2026 (Current: $(date)). Waiting for NTP sync..."
		sleep 3
	done
	echo "[WATCHDOG] System clock verified: $(date)"

	# 啟動前先刪除舊的健康與點火標記
	rm -f "$BOOT_FILE" "$HEALTH_FILE"

	# 🎯 終極修正：取得目前實體槽位的名字 (小寫，如 slot_a 或 slot_b)
	SLOT_NAME=$(basename "$CURRENT_SLOT" | tr '[:upper:]' '[:lower:]')

	echo "[WATCHDOG] Starting containers in $SLOT_NAME ..."

	# 🎯 透過 -p $SLOT_NAME 強制隔離專案名稱，
	# 這樣 slot_A 編譯出來的 Image 叫 slot_a-app，slot_B 叫 slot_b-app，快取完美隔離！
	docker compose -p "$SLOT_NAME" -f "$DOCKER_COMPOSE_FILE" down 2>/dev/null
	docker compose -p "$SLOT_NAME" -f "$DOCKER_COMPOSE_FILE" build
	docker compose -p "$SLOT_NAME" -f "$DOCKER_COMPOSE_FILE" up -d

	# --- 階段一：等待 Python 點火 (防範語法錯誤、環境噴掉、Docker卡死) ---
	echo "[WATCHDOG] Stage 1: Waiting for Python Bootstrap (Timeout: 60s)..."
	for i in {1..60}; do
		if [ -f "$BOOT_FILE" ]; then
			echo "[WATCHDOG] Stage 1 PASSED: Python core container alive."
			break
		fi
		if [ $i -eq 60 ]; then
			echo "[WATCHDOG] CRITICAL: Python failed to boot within 60s."
			return 1
		fi
		sleep 1
	done

	# --- 階段二：等待硬體自檢與潛在的 OTA 下載 (Timeout: 120s) ---
	echo "[WATCHDOG] Stage 2: Waiting for Hardware Self-test & OTA check (Timeout: 120s)..."
	for i in {1..120}; do
		# A. 成功情境：沒有更新，且硬體百分之百全過，進入 Standby Loop
		if [ -f "$HEALTH_FILE" ]; then
			echo "[WATCHDOG] SUCCESS! Known Good Version (KGV) locked on $(basename "$CURRENT_SLOT")."
			# 🟢 【新增：新版順利存活，清除嘗試紀錄】
			rm -f "$DATA_DIR/.ota_attempt"
			return 0
		fi

		# B. 退出情境：如果容器不見了 (因為發現 OTA 更新，主動 sys.exit(0) 停機)
		# 檢查 app 容器是否還在運行。若已經優雅退出，代表他正在發起 A/B 槽切換，不應該視為錯誤！
		if ! docker ps | grep -q "${SLOT_NAME}-app-1"; then
			echo "[WATCHDOG] Container exited early. Checking if OTA requested..."

			# 🎯 修正 2：嚴格區分「OTA 優雅退出」與「程式崩潰當機」
			if [ -f "$OTA_READY_FILE" ]; then
				# 確實是因為 OTA 準備重啟而退出的，交給常態迴圈處理，判定成功
				return 0
			else
				# 容器死掉了，卻沒有留下 OTA 標記，代表是發生了 Fatal Crash！
				echo "[WATCHDOG] CRITICAL FAILURE: Container crashed unexpectedly without OTA request!"
				return 1 # 判定失敗，立刻觸發緊急回滾！
			fi
		fi

		sleep 1
	done

	echo "[WATCHDOG] CRITICAL FAILURE: Hardware self-test timeout."
	return 1
}

# ==============================================================================
# 4. 啟動與自動回滾邏輯 (Rollback Logic)
# ==============================================================================
if ! start_and_verify; then
	echo "[WATCHDOG] CRITICAL FAILURE: Health check timeout."

	# 檢查備用槽是否有 Compose 檔 (若無，代表是出廠首刷失敗，無路可退)
	if [ -f "$ALT_SLOT/$DOCKER_COMPOSE_FILE" ]; then
		echo "[WATCHDOG] Triggering EMERGENCY ROLLBACK to $(basename "$ALT_SLOT")..."

		# 🔴 【新增：黑名單制裁】
		# 發現有未清除的 ota_attempt，代表剛剛死掉的那包韌體是新下載的，立刻抄進黑名單！
		if [ -f "$DATA_DIR/.ota_attempt" ]; then
			echo "[WATCHDOG] Blacklisting crashed firmware hash..."
			cat "$DATA_DIR/.ota_attempt" >>"$DATA_DIR/ota_blacklist.txt"
			echo "" >>"$DATA_DIR/ota_blacklist.txt" # 確保換行
			rm -f "$DATA_DIR/.ota_attempt"
		fi

		# 關閉失敗的容器
		FAILED_SLOT_NAME=$(basename "$CURRENT_SLOT" | tr '[:upper:]' '[:lower:]')
		cd "$CURRENT_LINK" && docker compose -p "$FAILED_SLOT_NAME" -f "$DOCKER_COMPOSE_FILE" down 2>/dev/null

		ln -sfn "$ALT_SLOT" "$CURRENT_LINK"
		CURRENT_SLOT="$ALT_SLOT"

		# 再次嘗試啟動舊版
		if start_and_verify; then
			echo "[WATCHDOG] Rollback successful. System recovered to previous KGV."
		else
			echo "[WATCHDOG] FATAL: Rollback failed. System is completely broken."
			exit 1
		fi
	else
		echo "[WATCHDOG] FATAL: No valid alternative slot for rollback. Exiting."
		exit 1
	fi
fi

# ==============================================================================
# 5. 常態監控與 OTA 觸發 (Steady State & OTA Trigger)
# ==============================================================================
echo "[WATCHDOG] Entering steady state monitoring..."
while true; do
	if [ -f "$OTA_READY_FILE" ]; then
		echo "[WATCHDOG] OTA Ready signal detected! Initiating A/B switch..."
		rm -f "$OTA_READY_FILE"

		if [ -f "$UPDATE_TAR" ]; then
			echo "[WATCHDOG] Extracting update to $(basename "$ALT_SLOT")..."
			# 清空備用槽，解壓縮新韌體
			rm -rf "$ALT_SLOT"/*
			tar -xzf "$UPDATE_TAR" -C "$ALT_SLOT"

			echo "[WATCHDOG] Stopping current slot containers..."
			# 🎯 修正：同步加上當前槽位名稱，精準關閉對應容器
			SLOT_NAME=$(basename "$CURRENT_SLOT" | tr '[:upper:]' '[:lower:]')
			cd "$CURRENT_LINK" && docker compose -p "$SLOT_NAME" -f "$DOCKER_COMPOSE_FILE" down

			echo "[WATCHDOG] Switching symlink to $(basename "$ALT_SLOT")..."
			ln -sfn "$ALT_SLOT" "$CURRENT_LINK"

			echo "[WATCHDOG] Rebooting watchdog to apply new slot..."
			# 🎯 直接結束腳本。systemd 會因為 Restart=always 在幾秒後重啟本腳本。
			# 重啟後，它會讀到新的 CURRENT_LINK，並進入第 3 步的 start_and_verify！
			exit 0
		else
			echo "[WATCHDOG] Update tarball missing! Canceling OTA."
		fi
	fi
	sleep 5
done
